<wsdl:definitions
     name="BPELProcess1"
     targetNamespace="http://xmlns.oracle.com/ReplicateApplication/Project1/BPELProcess1"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:client="http://xmlns.oracle.com/ReplicateApplication/Project1/BPELProcess1"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
    >
    <plnk:partnerLinkType name="BPELProcess1">
        <plnk:role name="BPELProcess1Provider" portType="client:BPELProcess1"/>
    </plnk:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/ReplicateApplication/Project1/BPELProcess1" schemaLocation="../Schemas/BPELProcess1.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="BPELProcess1RequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:portType name="BPELProcess1">
        <wsdl:operation name="process">
            <wsdl:input message="client:BPELProcess1RequestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
